### ISSUE TITLE
Understanding of dnn_activation

### ISSUE THREAD

**Issue by helloTC** [BNUCNL/dnnbrain#141]
Hi, I tried to use _dnn_activation_ extract activation (dnn.analyzer) from different model layers, while I found the annotation of the dnn_activation is not clear for me. 
I list the original annotation here,

>  Extract DNN activation from the specified layer
>     Parameters:
>     ----------
>     data[tensor]: input stimuli of the model with shape as (n_stim, n_chn, n_r, n_c)
>     model[model]: DNN model
>     layer_loc[sequence]: a sequence of keys to find the location of
>         the target layer in the DNN model.
>     channels[list]: channel indices of interest
>     Return:
>     ------
>     dnn_acts[array]: DNN activation
>         a 4D array with its shape as (n_stim, n_chn, n_r, n_c)

What makes me confuse is 
1) **the input of data.** Looks like the shape of input is same to the output (dnn_acts), while actually they're different. I finally understand the input of data is image tensor, while _dnn_acts_ is the actual DNN activation. **The shapes of n_chn, n_r and n_c have different meaning between data and dnn_acts.** Perhaps renaming data with shape as a different variable is better?
2) **The meaning of layer_loc.** **I have no idea about the meaning of 'sequence'. and what's the difference between 'sequence' and 'list'.** I then checked the source code of _dnn_act_ from command line, then found layer_loc is actually a tuple. But for a user it's merely possible to have an idea to generate layer_loc from NetLoader, and **the annotation itself is unclear to direct me to give a two-element tuple as an parameter to this function.** Maybe this annotation could be modified so that more friendly to users?

**Comment by sunshineDrizzle** [comment]
Reply to Q1:
    I agree with you, maybe the input stimuli tensor's shape can be renamed as (n_stim, n_chn, height, width)

Reply to Q2:
    I will add an example in the annotation in future.

**Comment by helloTC** [comment]
> Reply to Q1:
> I agree with you, maybe the input stimuli tensor's shape can be renamed as (n_stim, n_chn, height, width)
> 
> Reply to Q2:
> I will add an example in the annotation in future.

Thanks for that!
